### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by luoxiaozero** [thaw-ui/thaw#11]
## Roadmap

* 0.1.0-alpha
- [x] Binder. for AutoComplete, ColorPicker, Select.
- [x] Upload component click error.
- [x] Features tracing, GridItem span attribute conflict.
- [x] Internal component classification.

* 0.1.0-beta
- [x] Fix bugs.
- [x] Document writing.
- [x] Audit public interface.

* 0.1.0
- [x] Initial support SSR.
- [x] CI
- [x] Github page supports mobile viewing
- [ ] Document writing.
- [ ] More component.
- [ ] [WAI-ARIA guidelines](https://www.w3.org/WAI/ARIA/apg/)

* 0.2.0
Full support for SSR.

**Comment by qrilka** [comment]
I guess #72 should be linked to this one

**Comment by luoxiaozero** [comment]
Yes, I will unify it after 0.2 is officially released.
