### ISSUE TITLE
Roadmap: 0.2 (draft)

### ISSUE THREAD

**Issue by luoxiaozero** [thaw-ui/thaw#72]
This is a draft of version 0.2.

Under development on the main branch

## Roadmap

* [x] Remove the default feature of csr.
* [x] icondata was upgraded to v0.3.
* [x] [Controlled manner & uncontrolled manner](https://www.naiveui.com/en-US/os-theme/docs/controlled-uncontrolled) (Change RwSignal to Model. Allows `RwSignal` `(ReadSignal, None)` `(None, SignalSetter)` to be converted to Model.)
* [x] Change most of `#[prop(optional)] T` to `#[prop(optional)] Option<T>`
* [x] leptos updated to v0.6.0.
* [x] `ButtonVariant::Solid` is changed to `ButtonVariant::Outlined`
* [x] `Checkbox` children can be empty.
* [x]  Rewrite `Code` component.

**Comment by qrilka** [comment]
All the items seems to be checked - when 0.2 is supposed to land on crates.io?

**Comment by luoxiaozero** [comment]
These days are busy, I will probably release 0.2 in this day or two.
